apiVersion: apps/v1
kind: Deployment
metadata:
  name: agentic-ai-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: agentic-ai
  template:
    metadata:
      labels:
        app: agentic-ai
    spec:
      containers:
      - name: frontend
        image: arya518/agentic-ai-frontend:latest

        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: agentic-ai-service
spec:
  selector:
    app: agentic-ai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
